name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/topvennie/portfolio
          docker build . -t $IMAGE:pr-${{ github.sha }}
          if [ "${{ github.event_name }}" == "push" ]; then
            docker tag $IMAGE:pr-${{ github.sha }} $IMAGE:latest
          fi

      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push --all-tags ghcr.io/topvennie/portfolio
